site_name: Alinea
copyright: Copyright &copy; 2022 Idar Bergli
repo_name: idarb-oss/alinea-doc
repo_url: https://github.com/idarb-oss/alinea-doc

nav:
  - Home: 'index.md'
  #- 'Quick Start': 'quick-start.md'
  - Standardization:
      - Overview: 'standardization/overview.md'
      - 'API Design Guide':
        - Introduction: 'standardization/apis/introduction.md'
        - 'Resource Oriented Design': 'standardization/apis/resource-oriented-design.md'
        - 'Resource Names': 'standardization/apis/resource-names.md'
        - 'Standard Methods': 'standardization/apis/standard-methods.md'
        - 'Custom Methods': 'standardization/apis/custom-methods.md'
        - 'Standard Fields': 'standardization/apis/standard-fields.md'
        - 'Errors': 'standardization/apis/errors.md'
        - 'Naming Convention': 'standardization/apis/naming-conventions.md'
        - 'Design Patterns': 'standardization/apis/design-paterns.md'
        - 'System Parameters': 'standardization/apis/system-parameters.md'
        - 'Changelog': 'standardization/apis/changelog.md'
  - Architecture:
    - 'Components': 'architecture/components.md'
    - 'Hardware': 'architecture/hardware.md'
  - Services:
    - Overview: 'services/index.md'
    - 'Configuration Manager':
      - Overview: 'services/configuration-management/index.md'
      - Domain: 'services/configuration-management/domain.md'
      - Architecture: 'services/configuration-management/architecture.md'
    - 'Feature Flagging':
      - Overview: 'services/feature-flagging/index.md'
      #- Domain: 'services/configuration-management/domain.md'
      #- Architecture: 'services/configuration-management/architecture.md'
  - 'Decission Log':
    - Overview: 'decission-log/overview.md'
    - ADR:
      - 0001-record-architecture-descisions: 'decission-log/adr/0001-record-architecture-decisions.md'
      - 0002-use-modular-monolith-architecture: 'decission-log/adr/0002-use-modular-monolith-architecture.md'
      - 0003-use-dotnetcore-and-csharp: 'decission-log/adr/0003-use-dotnetcore-and-csharp.md'
      - 0004-create-facade-between-api-and-business-module: 'decission-log/adr/0004-create-facade-between-api-and-business-module.md'
      - 0005-use-cqrs-architectural-style: 'decission-log/adr/0005-use-cqrs-architectural-style.md'
      - 0006-allow-return-result-after-command-processing: 'decission-log/adr/0006-allow-return-result-after-command-processing.md'
      - 0007-use-feature-slicing: 'decission-log/adr/0007-use-feature-slicing.md'
      - 0008-create-rich-domain-models: 'decission-log/adr/0008-create-rich-domain-models.md'
      - 0009-use-domain-driven-design-tactical-patterns: 'decission-log/adr/0009-use-domain-driven-design-tactical-patterns.md'
      - 0010-protect-business-invariants-using-exceptions: 'decission-log/adr/0010-protect-business-invariants-using-exceptions.md'
      - 0011-event-driven-communication-between-modules: 'decission-log/adr/0011-event-driven-communication-between-modules.md'


theme:
  name: material
  palette:
    #scheme: slate
    primary: teal
    accent: 'deep orange'
  font:
    code: Roboto Mono
  language: en
  icon:
    logo: fontawesome/solid/paragraph
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide

plugins:
  - search:
      prebuild_index: true
  - git-revision-date:

extra:
  version:
    provider: mike
#  alternate:
#    - name: English
#      link: /en/
#      lang: en

markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

