site_name: Alinea
copyright: Copyright &copy; 2021 - 2021 Idar Bergli
repo_name: idarb-oss/alinea-doc
repo_url: https://github.com/idarb-oss/alinea-doc

nav:
  - Home: 'index.md'
  #- 'Quick Start': 'quick-start.md'
  - Standardisation:
      - Overview: 'standardisation/overview.md'
      - 'Multi-tenant': standardisation/multi-tenant.md
      - 'API Design Guide':
        - Introduction: 'standardisation/apis/introduction.md'
        - 'Resource Oriented Design': 'standardisation/apis/resource-oriented-design.md'
        - 'Resource Names': 'standardisation/apis/resource-names.md'
        - 'Standard Methods': 'standardisation/apis/standard-methods.md'
        - 'Custom Methods': 'standardisation/apis/custom-methods.md'
        - 'Standard Fields': 'standardisation/apis/standard-fields.md'
        - 'Errors': 'standardisation/apis/errors.md'
        - 'Naming Convention': 'standardisation/apis/naming-conventions.md'
        - 'Design Patterns': 'standardisation/apis/design-paterns.md'
        - 'System Parameters': 'standardisation/apis/system-parameters.md'
        - 'Changelog': 'standardisation/apis/changelog.md'
      - 'Metadata': standardisation/metadata.md
  - Architecture:
    - 'Components': 'architecture/components.md'
  - Libraries:
    - Overview: 'libs/overview.md'
    - Python:
      - Core: 'libs/python/core.md'
  - Services:
    - Overview: 'services/overview.md'
  - 'Decission Log':
    - Overview: 'decission-log/overview.md'


theme:
  name: material
  palette:
    #scheme: slate
    primary: teal
    accent: 'deep orange'
  font:
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide

plugins:
  - search:
      prebuild_index: true
  - git-revision-date:

extra:
  version:
    provider: mike
#  alternate:
#    - name: English
#      link: /en/
#      lang: en

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
