site_name: Alinea
copyright: Copyright &copy; 2021 - 2021 Idar Bergli
repo_name: idarb-oss/alinea-doc
repo_url: https://github.com/idarb-oss/alinea-doc

nav:
  - Home: 'index.md'
  - Design:
    - Overview: 'design/overview.md'
    - 'Domain Driven Design': 'design/ddd.md'
    - Standardization:
      - Overview: 'design/standardization/overview.md'
      - 'API Design Guide':
        - Introduction: 'design/standardization/apis/introduction.md'
        - 'Resource Oriented Design': 'design/standardization/apis/resource-oriented-design.md'
        - 'Resource Names': 'design/standardization/apis/resource-names.md'
        - 'Standard Methods': 'design/standardization/apis/standard-methods.md'
        - 'Custom Methods': 'design/standardization/apis/custom-methods.md'
        - 'Standard Fields': 'design/standardization/apis/standard-fields.md'
        - 'Errors': 'design/standardization/apis/errors.md'
        - 'Naming Convention': 'design/standardization/apis/naming-conventions.md'
        - 'Design Patterns': 'design/standardization/apis/design-paterns.md'
        - 'System Parameters': 'design/standardization/apis/system-parameters.md'
        - 'Changelog': 'design/standardization/apis/changelog.md'
    - Architecture:
      - 'Overview': 'design/architecture/overview.md'
  - Services:
    - Overview: 'services/overview.md'
    - 'Tenant System': 'services/tenant-manager.md'
    - 'Project System': 'services/project-manager.md'
  - Libraries:
    - Overview: 'libs/overview.md'
    - Dotnet:
      - Overview: 'libs/dotnet/overview.md'
  - 'Decission Log':
    - Overview: 'decission-log/overview.md'


theme:
  name: material
  palette:
    #scheme: slate
    primary: teal
    accent: 'deep orange'
  font:
    code: Roboto Mono
  language: en
  icon:
    logo: fontawesome/solid/paragraph
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - header.autohide

plugins:
  - search:
      prebuild_index: true
  - git-revision-date:

extra:
  version:
    provider: mike
#  alternate:
#    - name: English
#      link: /en/
#      lang: en

markdown_extensions:
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

