@startuml C3 Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(c1, "Alinea") {
    Container(frontend, "Web Frontend", "", "GUI for the application")
    
    ComponentQueue(eventBus, "Events Bus", "Integration Events")
    
    Boundary(myMeetingsApi, "Alinea Backend") {
        Component(api, "API", ".NET Core API")
        Component(backendForFrontend, "Backend for Frontend", ".NET Core API")
        Component(configMgmt, "Configuration Management", ".NET Libraries")
    }
    
    Boundary(database, "Database") {
        ComponentDb(configMgmtData, "Configuration Management data", "schema")
    }
}

System_Ext(service, "Service", "")
    
Rel(frontend, backendForFrontend, "Uses", "HTTP")
Rel(backendForFrontend, api, "Uses", "HTTP")
Rel(api, configMgmt, "Uses")

Rel(configMgmt, eventBus, "Integration Events", "Publish/Subscribe")

Rel(configMgmt, configMgmtData, "Store / retrieve")

Rel(service, api, "Get configuration", "HTTP/Websocket")

LAYOUT_WITH_LEGEND()

@enduml